spring.application.name=folha-pagamento

spring.datasource.url=jdbc:postgresql://localhost:5432/folha_pagamento
spring.datasource.username=postgres
spring.datasource.password=malgi2016

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true